---
title: "Money Growth Rate vs. Inflation Rate"
# output: html_notebook
---

#############################################################################################
# Project: FOMC 2019
# Economist: Ravi
# RA: Brian Reinbold
# Last Edited: 11/14/2019
#

#############################################################################################

```{r}
library(tidyverse)
library(readxl)


rm(list=ls())

# directories
path <- "G:/Research_Analyst/Reinbold/Ravi/FOMC 2019"
input_dir <- "/Data/"
output_dir <- "/Output/"

```

```{r}
### read in data ###

# Monthly CPI and M1 1959-2019
monthly_raw <- read_excel(paste0(path, input_dir, "M1 CPI Data.xlsx"),
                  sheet = "Monthly",
                  skip  = 3,
                  col_names = FALSE
                  )
monthly_raw <- monthly_raw[, 2:4]         # subset of excel date and raw data
colnames(monthly_raw) <- c("date", "price", "m1")

# Annual CPI and M1 1959-2018
annual_raw <- read_excel(paste0(path, input_dir, "M1 CPI Data.xlsx"),
                  sheet = "Annual",
                  skip  = 3,
                  col_names = FALSE
                  )
annual_raw <- annual_raw[, 1:3]         # subset raw data
colnames(annual_raw) <- c("year", "price", "m1")

# Historical Data for Lucas Paper
historical_raw <- read_excel(paste0(path, input_dir, "Lucas Data.xlsx"),
                  sheet = "Data"
                  )
colnames(historical_raw) <- c("year", "gdp", "price", "m1", "rate")

### make decade data frame ###
# For each year from 1900-2018, classify decade
# eg. 1905: Decade = 1900-1909
decade_df <- data.frame(year = seq(1900, 2019, by = 1))            # initialize df with years
decade_df <- decade_df %>%
  # find beginning of decade by taking modulus, eg. 1900, 1910, ....
  mutate(.,
         decadeBeg = if_else(year %% 10 == 0,                      # year %% 10 == year mod 10        
                             year,
                             as.numeric(NA)
                             )
         ) %>%
  mutate(., decadeEnd = decadeBeg + 9) %>%                         # end of decade is beginning + 9
  mutate_at(., .vars = c("decadeBeg", "decadeEnd"),                # fill in NAs
               .funs = ~(zoo::na.locf(.))
            ) %>%
  mutate(., Decade = paste(decadeBeg, decadeEnd, sep = "-"))       # combine to make Decade indicator

# historical data ends in 2018
decadeHist_df <- data.frame(year = seq(1900, 2018, by = 1))        # initialize df with years
decadeHist_df <- decadeHist_df %>%
  # find beginning of decade by taking modulus, eg. 1900, 1910, ....
  mutate(.,
         decadeBeg = if_else(year %% 10 == 0,                      # year %% 10 == year mod 10        
                             year,
                             as.numeric(NA)
                             )
         ) %>%
  mutate(., decadeEnd = decadeBeg + 9) %>%                         # end of decade is beginning + 9
  mutate_at(., .vars = c("decadeBeg", "decadeEnd"),                # fill in NAs
               .funs = ~(zoo::na.locf(.))
            ) %>%
  mutate(., decadeEnd = if_else(decadeEnd == 2019,                 # don't have 2019 data so make it end
                                2018,                              # in 2018 instead
                                decadeEnd
                                )
         ) %>%
  mutate(., Decade = paste(decadeBeg, decadeEnd, sep = "-"))   

```


```{r}
### Clean Data and Do Calcs ###

# monthly data
monthly_df <- monthly_raw %>%
  mutate(., `Inflation Rate`    = price / lag(price) - 1,
            `Money Growth Rate` = m1 / lag(m1) - 1,
            year                = lubridate::year(date),
            month               = lubridate::month(date)
            ) %>%
  left_join(., decade_df, by = "year")

# annulize monthly data
annual_df <- monthly_df %>%
  group_by(., year) %>%
  summarise_at(., .vars = c("Inflation Rate", "Money Growth Rate"),
                  .funs = ~(mean(., na.rm = TRUE))
               )

# average by decade
decade_df <- monthly_df %>%
  group_by(., Decade) %>%
  summarise_at(., .vars = c("Inflation Rate", "Money Growth Rate"),
                  .funs = ~(mean(., na.rm = TRUE))
               )

```


```{r}
### Clean Annual Historical Data and Do Calcs ###

df <- historical_raw %>%
  mutate(., year = as.numeric(year)) %>%
  mutate(., `Inflation Rate`    = price / lag(price) - 1,
            `Money Growth Rate` = m1 / lag(m1) - 1
            ) %>%
  left_join(., decadeHist_df, by = "year")

# calc decade average of each rate 
avgDec_df <- df %>%
  group_by(., Decade) %>%
  summarise_at(., vars("Inflation Rate", "Money Growth Rate"), 
               .funs = ~(mean(., na.rm = TRUE))
               )
# # calc decade growth rate
# decGrowth_df <- df %>%
#   filter(., year == decadeBeg | year == decadeEnd | year == 2018) %>%
#   mutate(., `Inflation Rate`    = price / lag(price) - 1,
#             `Money Growth Rate` = m1 / lag(m1) - 1,
#             ) %>%
#   filter(., year %% 10 == 9 | year == 2018)
# 
historicalData <- list("annual"    = df,
               "avgDec"    = avgDec_df
               )
  
rm(df, avgDec_df)


```



```{r}
graph_scatter <- function(data_df, title) {
  
  g <- ggplot(data = data_df, aes(x = `Money Growth Rate`, y = `Inflation Rate`)) +
    theme_bw(20) + 
    geom_point() +
    geom_smooth(method = "lm") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 8),
                       labels = scales::percent_format(accuracy = 0.05)
                       ) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 8),
                       labels = scales::percent_format(accuracy = 0.05)
                       ) +
    theme(legend.title = element_blank(),
          legend.position = c(0.85, 0.85)
          ) +
    ggtitle(title) +
    labs(x = "Money Growth Rate",
         y = "Inflation Rate"
         )
  
  # Export
  ggsave(filename = paste0(path, output_dir, title, ".png"),
         plot     = g,
         width    = 12,
         height   = 8,
         units    = "in"
         )
  
  return(g)
}


```

```{r}
#### Monthly Data ###
graph_scatter(data_df = monthly_df,
              title   = "Month-Month Growth Rate of CPI and M1 (1960-2019)"
              )
```


```{r}
#### Annual Data ###
graph_scatter(data_df = annual_df,
              title   = "Annual Growth Rate of CPI and M1 (1960-2019)"
              )
# Average Decade growth rate of annual data
graph_scatter(data_df = decade_df,
              title   = "Average Decade Growth Rate of CPI and M1 (1960-2019)"
              )

```

```{r}
#### Historical Data ###
graph_scatter(data_df = historicalData$annual,
              title   = "Annual Growth Rate of GDP Deflator and M1 (1900-2018)"
              )
# Average Decade growth rate of annual data
graph_scatter(data_df = historicalData$avgDec,
              title   = "Average Decade Growth Rate of GDP Deflator and M1 (1900-2018)"
              )
```